create table Todo (id bigint generated by default as identity, description varchar(255), summary varchar(255), primary key (id));

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );
